name: Fetch apt dependecys or load them from cach

env:

jobs:
  fetch_deps:
    runs-on: ubuntu-latest

    steps:

    - name: Get apt dependencies
      run: sudo apt update && sudo apt install -y mingw-w64 vcpkg ninja cmake unzip

    - name: Get MASM assembler
      run: wget https://github.com/Terraspace/UASM/files/9881874/uasm256_linux64.zip && unzip uasm256_linux64.zip && chmod +x uasm && sudo mv uasm /bin/

    - name: Test dependencies
      run: uasm -h
