name: Fetch apt dependecys or load them from cach

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:

      #- name: Get apt dependencies
      #run: sudo apt update && sudo apt install -y build-essential pkg-config mingw-w64 ninja-build cmake unzip
      #
    - name: Cach apt dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: build-essential pkg-config mingw-w64 ninja-build cmake unzip

    - name: Cach non apt dependencies
      id: cach-non-apt
      uses: actions/cache@v4
      with:
        path:
          /opt/vcpkg
          /usr/bin/vcpkg
          /usr/bin/uasm
          /opt/uasm
        key: non-apt-build-deps

    - if: ${{ steps.cache-non-apt.outputs.cache-hit != 'true' }}
      name: Get vcpkg
      run: wget -qO vcpkg.tar.gz https://github.com/microsoft/vcpkg/archive/master.tar.gz && sudo mkdir /opt/vcpkg && sudo tar xf vcpkg.tar.gz --strip-components=1 -C /opt/vcpkg && sudo /opt/vcpkg/bootstrap-vcpkg.sh && sudo ln -s /opt/vcpkg/vcpkg /usr/bin/vcpkg

    - if: ${{ steps.cache-non-apt.outputs.cache-hit != 'true' }}
      name: Get MASM assembler
      run: wget https://github.com/Terraspace/UASM/files/9881874/uasm256_linux64.zip && unzip uasm256_linux64.zip && chmod +x uasm && sudo cp uasm /opt/ && sudo ln -s /opt/uasm /usr/bin/uasm


    - if: ${{ steps.cache-non-apt.outputs.cache-hit != 'true' }}
      name: Get MASM assembler
      run: cp uasm sudo ln -s ~/uasm /usr/bin/uasm

    - name: Test vcpkg
      run: ls -l /opt/vcpkg

    - name: Test vcpkg bin
      run: ls -l /usr/bin/vcpkg

    - name: Test uasm link
      run: ls -l /usr/bin/uasm

    - name: Test uasm
      run: ls -l ~
        #- name: Test dependencies
        #run: vcpkg --version && uasm -h && ninja --version && x86_64-w64-mingw32-g++ --version && x86_64-w64-mingw32-gcc --version && cmake --version

    
