name: Fetch apt dependecys or load them from cach

on: workflow_dispatch

jobs:
  fetch_deps:
    runs-on: ubuntu-latest

    steps:

    - name: Get apt dependencies
      run: sudo apt update && sudo apt install -y build-essential pkg-config mingw-w64 ninja-build cmake unzip

    - name: Get vcpkg
      run: wget -qO vcpkg.tar.gz https://github.com/microsoft/vcpkg/archive/master.tar.gz && sudo mkdir /opt/vcpkg && sudo tar xf vcpkg.tar.gz --strip-components=1 -C /opt/vcpkg && sudo /opt/vcpkg/bootstrap-vcpkg.sh

    - name: Get MASM assembler
      run: wget https://github.com/Terraspace/UASM/files/9881874/uasm256_linux64.zip && unzip uasm256_linux64.zip && chmod +x uasm && sudo mv uasm /usr/local/bin/uasm

    - name: Test dependencies
      run: vcpkg --version && uasm -h && ninja --version && x86_64-w64-mingw32-g++ --version && x86_64-w64-mingw32-gcc --version && cmake --version
